INSERT INTO "sponsor_sponsor" VALUES(1,'canonical','Canonical Limited','gold','http://www.canonical.com/','*','*','*','canonical.png',5);
INSERT INTO "sponsor_sponsor" VALUES(2,'catalyst','Catalyst IT Liimited','gold','http://catalyst.net.nz/','*','*','*','catalyst.png',5);
INSERT INTO "sponsor_sponsor" VALUES(3,'weta-digital','Weta Digital Limited','gold','http://www.wetafx.co.nz/','*','*','*','weta.jpg',5);
INSERT INTO "sponsor_sponsor" VALUES(4,'psf','Python Software Foundation','gold','http://www.python.org/psf/','*','*','*','psf.png',5);
INSERT INTO "sponsor_sponsor" VALUES(5,'unfold','Unfold Limited','gold','http://www.unfold.co.nz/','*','*','*','unfold.png',5);
INSERT INTO "sponsor_sponsor" VALUES(6,'tait','Tait Radio Communications','gold','http://www.tait.co.nz/','*','*','*','tait.png',5);
INSERT INTO "sponsor_sponsor" VALUES(7,'encode','Encode Limited','silver','http://encode.net.nz/','*','*','*','encode.png',2);
INSERT INTO "sponsor_sponsor" VALUES(8,'powerhouse-ventures','powerHouse Ventures Limited','silver','http://www.powerhouse-ventures.co.nz/','*','*','*','powerhouse.png',2);
INSERT INTO "sponsor_sponsor" VALUES(9,'pretaweb','PretaWeb','silver','http://www.pretaweb.com/','*','*','*','pretaweb.png',2);
INSERT INTO "sponsor_sponsor" VALUES(10,'vortexdna','VortexDNA','silver','http://www.vortexdna.com/','*','*','*','vortex.png',2);
INSERT INTO "sponsor_sponsor" VALUES(11,'apress','Apress','schwag','http://apress.com/','*','*','*','apress.png',0);
INSERT INTO "sponsor_sponsor" VALUES(12,'oreilly','O''Reilly','schwag','http://www.oreilly.com/','*','*','*','oreilly.png',0);
INSERT INTO "sponsor_sponsor" VALUES(13,'webstock','Webstock','schwag','http://www.webstock.org.nz/','*','*','*','webstock.png',0);
INSERT INTO "sponsor_sponsor" VALUES(14,'packt','Packt Publishing','schwag','http://www.packtpub.com/','*','*','*','packt.png',0);
